
[
  { 
    "Category": "category1",
    "Planning Pathway": "Complying Development",
    "Development Type": "Outbuilding (Garage)",
    "Zone": "R1",
    "Zone Description": "General Residential",
    "Minimum Lot Size (sqm)": "450",
    "Minimum Lot Width (m)": "15",
    "Minimum Front Setback (m)": "4.5",
    "Minimum Side Setback (m)": "0.9",
    "Minimum Rear Setback (m)": "3",
    "Maximum Percentage of Lot Used (%)": "0.5",
    "Maximum Area (sqm)": "60",
    "Maximum Building Height (m)": "3.5",
    "Additional Criteria": "No more than 1 garage per lot"
  },
  {
    "Category": "category2",
    "Planning Pathway": "Complying Development",
    "Development Type": "Outbuilding (Garage)",
    "Zone": "R2",
    "Zone Description": "Low-Density Residential",
    "Minimum Lot Size (sqm)": "500",
    "Minimum Lot Width (m)": "15",
    "Minimum Front Setback (m)": "6",
    "Minimum Side Setback (m)": "0.9",
    "Minimum Rear Setback (m)": "3",
    "Maximum Percentage of Lot Used (%)": "0.5",
    "Maximum Area (sqm)": "60",
    "Maximum Building Height (m)": "3.5",
    "Additional Criteria": "No garage in front setback zone"
  },
  {
    "Category": "category3",
    "Planning Pathway": "Complying Development",
    "Development Type": "Outbuilding (Garage)",
    "Zone": "R3",
    "Zone Description": "Medium-Density Residential",
    "Minimum Lot Size (sqm)": "400",
    "Minimum Lot Width (m)": "12",
    "Minimum Front Setback (m)": "4",
    "Minimum Side Setback (m)": "0.9",
    "Minimum Rear Setback (m)": "3",
    "Maximum Percentage of Lot Used (%)": "0.45",
    "Maximum Area (sqm)": "60",
    "Maximum Building Height (m)": "3.5",
    "Additional Criteria": "Materials must match existing house"
  },
  {
    "Category": "category4",
    "Planning Pathway": "Complying Development",
    "Development Type": "Outbuilding (Garage)",
    "Zone": "R4",
    "Zone Description": "High-Density Residential",
    "Minimum Lot Size (sqm)": "400",
    "Minimum Lot Width (m)": "12",
    "Minimum Front Setback (m)": "4",
    "Minimum Side Setback (m)": "0.9",
    "Minimum Rear Setback (m)": "3",
    "Maximum Percentage of Lot Used (%)": "0.45",
    "Maximum Area (sqm)": "60",
    "Maximum Building Height (m)": "3.5",
    "Additional Criteria": "Roof pitch ≤ 20 degrees"
  },
  {
    "Category": "category5",
    "Planning Pathway": "Complying Development",
    "Development Type": "Outbuilding (Garage)",
    "Zone": "R5",
    "Zone Description": "Large Lot Residential",
    "Minimum Lot Size (sqm)": "2000",
    "Minimum Lot Width (m)": "20",
    "Minimum Front Setback (m)": "10",
    "Minimum Side Setback (m)": "1.5",
    "Minimum Rear Setback (m)": "5",
    "Maximum Percentage of Lot Used (%)": "0.4",
    "Maximum Area (sqm)": "100",
    "Maximum Building Height (m)": "4",
    "Additional Criteria": "Screening required for adjacent properties"
  },
  {
    "Category": "category6",
    "Planning Pathway": "Complying Development",
    "Development Type": "Outbuilding (Garage)",
    "Zone": "RU1",
    "Zone Description": "Primary Production",
    "Minimum Lot Size (sqm)": "10000",
    "Minimum Lot Width (m)": "50",
    "Minimum Front Setback (m)": "10",
    "Minimum Side Setback (m)": "5",
    "Minimum Rear Setback (m)": "5",
    "Maximum Percentage of Lot Used (%)": "0.2",
    "Maximum Area (sqm)": "100",
    "Maximum Building Height (m)": "4.5",
    "Additional Criteria": "Flood-prone land restrictions apply"
  },
  {
    "Category": "category7",
    "Planning Pathway": "Complying Development",
    "Development Type": "Outbuilding (Garage)",
    "Zone": "RU2",
    "Zone Description": "Rural Landscape",
    "Minimum Lot Size (sqm)": "10000",
    "Minimum Lot Width (m)": "50",
    "Minimum Front Setback (m)": "10",
    "Minimum Side Setback (m)": "5",
    "Minimum Rear Setback (m)": "5",
    "Maximum Percentage of Lot Used (%)": "0.2",
    "Maximum Area (sqm)": "100",
    "Maximum Building Height (m)": "4.5",
    "Additional Criteria": "Must retain rural character"
  },
  {
    "Category": "category8",
    "Planning Pathway": "Complying Development",
    "Development Type": "Outbuilding (Garage)",
    "Zone": "RU4",
    "Zone Description": "Primary Production Small Lots",
    "Minimum Lot Size (sqm)": "4000",
    "Minimum Lot Width (m)": "25",
    "Minimum Front Setback (m)": "10",
    "Minimum Side Setback (m)": "2.5",
    "Minimum Rear Setback (m)": "5",
    "Maximum Percentage of Lot Used (%)": "0.3",
    "Maximum Area (sqm)": "80",
    "Maximum Building Height (m)": "4",
    "Additional Criteria": "Vegetation clearance limited"
  },
  {
    "Category": "category9",
    "Planning Pathway": "Complying Development",
    "Development Type": "Outbuilding (Garage)",
    "Zone": "RU5",
    "Zone Description": "Village",
    "Minimum Lot Size (sqm)": "2000",
    "Minimum Lot Width (m)": "20",
    "Minimum Front Setback (m)": "6",
    "Minimum Side Setback (m)": "1.5",
    "Minimum Rear Setback (m)": "3",
    "Maximum Percentage of Lot Used (%)": "0.35",
    "Maximum Area (sqm)": "80",
    "Maximum Building Height (m)": "4",
    "Additional Criteria": "Heritage controls may apply"
  },
  {
    "Category": "category10",
    "Planning Pathway": "Complying Development",
    "Development Type": "Outbuilding (Garage)",
    "Zone": "E2",
    "Zone Description": "Environmental Conservation",
    "Minimum Lot Size (sqm)": "5000",
    "Minimum Lot Width (m)": "50",
    "Minimum Front Setback (m)": "20",
    "Minimum Side Setback (m)": "10",
    "Minimum Rear Setback (m)": "10",
    "Maximum Percentage of Lot Used (%)": "0.1",
    "Maximum Area (sqm)": "50",
    "Maximum Building Height (m)": "4",
    "Additional Criteria": "Must be designed to minimize visual impact"
  },
  {
    "Category": "category11",
    "Planning Pathway": "Complying Development",
    "Development Type": "Outbuilding (Garage)",
    "Zone": "E4",
    "Zone Description": "Environmental Living",
    "Minimum Lot Size (sqm)": "4000",
    "Minimum Lot Width (m)": "30",
    "Minimum Front Setback (m)": "15",
    "Minimum Side Setback (m)": "5",
    "Minimum Rear Setback (m)": "5",
    "Maximum Percentage of Lot Used (%)": "0.2",
    "Maximum Area (sqm)": "60",
    "Maximum Building Height (m)": "3.5",
    "Additional Criteria": "Bushfire management plan required"
  },
  {
    "Category": "category12",
    "Planning Pathway": "Complying Development",
    "Development Type": "Outbuilding (Garage)",
    "Zone": "SP3",
    "Zone Description": "Tourist",
    "Minimum Lot Size (sqm)": "1000",
    "Minimum Lot Width (m)": "20",
    "Minimum Front Setback (m)": "10",
    "Minimum Side Setback (m)": "2.5",
    "Minimum Rear Setback (m)": "5",
    "Maximum Percentage of Lot Used (%)": "0.25",
    "Maximum Area (sqm)": "80",
    "Maximum Building Height (m)": "4",
    "Additional Criteria": "Must align with tourist facility aesthetics"
  },
  {
    "Category": "category13",
    "Planning Pathway": "Complying Development",
    "Development Type": "Outbuilding (Garage)",
    "Zone": "MU1",
    "Zone Description": "Mixed Use",
    "Minimum Lot Size (sqm)": "500",
    "Minimum Lot Width (m)": "15",
    "Minimum Front Setback (m)": "4",
    "Minimum Side Setback (m)": "0.9",
    "Minimum Rear Setback (m)": "3",
    "Maximum Percentage of Lot Used (%)": "0.5",
    "Maximum Area (sqm)": "60",
    "Maximum Building Height (m)": "3.5",
    "Additional Criteria": "No commercial use allowed in garage"
  },
  {
    "Category": "category14",
    "Planning Pathway": "Local Council",
    "Development Type": "Outbuilding (Garage)",
    "Zone": "Any",
    "Zone Description": "Any",
    "Minimum Lot Size (sqm)": "Any",
    "Minimum Lot Width (m)": "Any",
    "Minimum Front Setback (m)": "Any",
    "Minimum Side Setback (m)": "Any",
    "Minimum Rear Setback (m)": "Any",
    "Maximum Percentage of Lot Used (%)": "Any",
    "Maximum Area (sqm)": "Any",
    "Maximum Building Height (m)": "Any",
    "Additional Criteria": "Any"
  },
  {
    "Category": "category15",
    "Planning Pathway": "Local Council",
    "Development Type": "Outbuilding (Carport)",
    "Zone": "Any",
    "Zone Description": "Any",
    "Minimum Lot Size (sqm)": "Any",
    "Minimum Lot Width (m)": "Any",
    "Minimum Front Setback (m)": "Any",
    "Minimum Side Setback (m)": "Any",
    "Minimum Rear Setback (m)": "Any",
    "Maximum Percentage of Lot Used (%)": "Any",
    "Maximum Area (sqm)": "Any",
    "Maximum Building Height (m)": "Any",
    "Additional Criteria": "Any"
  },
  {
    "Category": "category16",
    "Planning Pathway": "Local Council",
    "Development Type": "New Dwelling",
    "Zone": "Any",
    "Zone Description": "Any",
    "Minimum Lot Size (sqm)": "Any",
    "Minimum Lot Width (m)": "Any",
    "Minimum Front Setback (m)": "Any",
    "Minimum Side Setback (m)": "Any",
    "Minimum Rear Setback (m)": "Any",
    "Maximum Percentage of Lot Used (%)": "Any",
    "Maximum Area (sqm)": "Any",
    "Maximum Building Height (m)": "Any",
    "Additional Criteria": "Any"
  }
]

column_mapping = {
    "Category": "category",
    "Planning Pathway": "planning_pathway",
    "Development Type": "development_type",
    "Zone": "zone",
    "Zone Description": "zone_description",
    "Minimum Lot Size (sqm)": "minimum_lot_size",
    "Minimum Lot Width (m)": "minimum_lot_width",
    "Minimum Front Setback (m)": "minimum_front_setback",
    "Minimum Side Setback (m)": "minimum_side_setback",
    "Minimum Rear Setback (m)": "minimum_real_setback",
    "Maximum Percentage of Lot Used (%)": "maximum_percentage_of_lot_used",
    "Maximum Area (sqm)": "maximum_area",
    "Maximum Building Height (m)": "maximum_building_height",
    "Additional Criteria": "additional_criteria"
}


def rename_columns(data_list, column_mapping):
    return [
        {column_mapping.get(k, k): v for k, v in item.items()}
        for item in data_list
    ]

# Renaming columns in Yo
renamed = rename_columns(Yo, column_mapping)

# Print or use the updated Yo list with renamed keys
from pprint import pprint
pprint(renamed)










[{'additional_criteria': 'No more than 1 garage per lot',
  'category': 'category1',
  'development_type': 'Outbuilding (Garage)',
  'maximum_area': '60',
  'maximum_building_height': '3.5',
  'maximum_percentage_of_lot_used': '0.5',
  'minimum_front_setback': '4.5',
  'minimum_lot_size': '450',
  'minimum_lot_width': '15',
  'minimum_real_setback': '3',
  'minimum_side_setback': '0.9',
  'planning_pathway': 'Complying Development',
  'zone': 'R1',
  'zone_description': 'General Residential'},
 {'additional_criteria': 'No garage in front setback zone',
  'category': 'category2',
  'development_type': 'Outbuilding (Garage)',
  'maximum_area': '60',
  'maximum_building_height': '3.5',
  'maximum_percentage_of_lot_used': '0.5',
  'minimum_front_setback': '6',
  'minimum_lot_size': '500',
  'minimum_lot_width': '15',
  'minimum_real_setback': '3',
  'minimum_side_setback': '0.9',
  'planning_pathway': 'Complying Development',
  'zone': 'R2',
  'zone_description': 'Low-Density Residential'},
 {'additional_criteria': 'Materials must match existing house',
  'category': 'category3',
  'development_type': 'Outbuilding (Garage)',
  'maximum_area': '60',
  'maximum_building_height': '3.5',
  'maximum_percentage_of_lot_used': '0.45',
  'minimum_front_setback': '4',
  'minimum_lot_size': '400',
  'minimum_lot_width': '12',
  'minimum_real_setback': '3',
  'minimum_side_setback': '0.9',
  'planning_pathway': 'Complying Development',
  'zone': 'R3',
  'zone_description': 'Medium-Density Residential'},
 {'additional_criteria': 'Roof pitch ≤ 20 degrees',
  'category': 'category4',
  'development_type': 'Outbuilding (Garage)',
  'maximum_area': '60',
  'maximum_building_height': '3.5',
  'maximum_percentage_of_lot_used': '0.45',
  'minimum_front_setback': '4',
  'minimum_lot_size': '400',
  'minimum_lot_width': '12',
  'minimum_real_setback': '3',
  'minimum_side_setback': '0.9',
  'planning_pathway': 'Complying Development',
  'zone': 'R4',
  'zone_description': 'High-Density Residential'},
 {'additional_criteria': 'Screening required for adjacent properties',
  'category': 'category5',
  'development_type': 'Outbuilding (Garage)',
  'maximum_area': '100',
  'maximum_building_height': '4',
  'maximum_percentage_of_lot_used': '0.4',
  'minimum_front_setback': '10',
  'minimum_lot_size': '2000',
  'minimum_lot_width': '20',
  'minimum_real_setback': '5',
  'minimum_side_setback': '1.5',
  'planning_pathway': 'Complying Development',
  'zone': 'R5',
  'zone_description': 'Large Lot Residential'},
 {'additional_criteria': 'Flood-prone land restrictions apply',
  'category': 'category6',
  'development_type': 'Outbuilding (Garage)',
  'maximum_area': '100',
  'maximum_building_height': '4.5',
  'maximum_percentage_of_lot_used': '0.2',
  'minimum_front_setback': '10',
  'minimum_lot_size': '10000',
  'minimum_lot_width': '50',
  'minimum_real_setback': '5',
  'minimum_side_setback': '5',
  'planning_pathway': 'Complying Development',
  'zone': 'RU1',
  'zone_description': 'Primary Production'},
 {'additional_criteria': 'Must retain rural character',
  'category': 'category7',
  'development_type': 'Outbuilding (Garage)',
  'maximum_area': '100',
  'maximum_building_height': '4.5',
  'maximum_percentage_of_lot_used': '0.2',
  'minimum_front_setback': '10',
  'minimum_lot_size': '10000',
  'minimum_lot_width': '50',
  'minimum_real_setback': '5',
  'minimum_side_setback': '5',
  'planning_pathway': 'Complying Development',
  'zone': 'RU2',
  'zone_description': 'Rural Landscape'},
 {'additional_criteria': 'Vegetation clearance limited',
  'category': 'category8',
  'development_type': 'Outbuilding (Garage)',
  'maximum_area': '80',
  'maximum_building_height': '4',
  'maximum_percentage_of_lot_used': '0.3',
  'minimum_front_setback': '10',
  'minimum_lot_size': '4000',
  'minimum_lot_width': '25',
  'minimum_real_setback': '5',
  'minimum_side_setback': '2.5',
  'planning_pathway': 'Complying Development',
  'zone': 'RU4',
  'zone_description': 'Primary Production Small Lots'},
 {'additional_criteria': 'Heritage controls may apply',
  'category': 'category9',
  'development_type': 'Outbuilding (Garage)',
  'maximum_area': '80',
  'maximum_building_height': '4',
  'maximum_percentage_of_lot_used': '0.35',
  'minimum_front_setback': '6',
  'minimum_lot_size': '2000',
  'minimum_lot_width': '20',
  'minimum_real_setback': '3',
  'minimum_side_setback': '1.5',
  'planning_pathway': 'Complying Development',
  'zone': 'RU5',
  'zone_description': 'Village'},
 {'additional_criteria': 'Must be designed to minimize visual impact',
  'category': 'category10',
  'development_type': 'Outbuilding (Garage)',
  'maximum_area': '50',
  'maximum_building_height': '4',
  'maximum_percentage_of_lot_used': '0.1',
  'minimum_front_setback': '20',
  'minimum_lot_size': '5000',
  'minimum_lot_width': '50',
  'minimum_real_setback': '10',
  'minimum_side_setback': '10',
  'planning_pathway': 'Complying Development',
  'zone': 'E2',
  'zone_description': 'Environmental Conservation'},
 {'additional_criteria': 'Bushfire management plan required',
  'category': 'category11',
  'development_type': 'Outbuilding (Garage)',
  'maximum_area': '60',
  'maximum_building_height': '3.5',
  'maximum_percentage_of_lot_used': '0.2',
  'minimum_front_setback': '15',
  'minimum_lot_size': '4000',
  'minimum_lot_width': '30',
  'minimum_real_setback': '5',
  'minimum_side_setback': '5',
  'planning_pathway': 'Complying Development',
  'zone': 'E4',
  'zone_description': 'Environmental Living'},
 {'additional_criteria': 'Must align with tourist facility aesthetics',
  'category': 'category12',
  'development_type': 'Outbuilding (Garage)',
  'maximum_area': '80',
  'maximum_building_height': '4',
  'maximum_percentage_of_lot_used': '0.25',
  'minimum_front_setback': '10',
  'minimum_lot_size': '1000',
  'minimum_lot_width': '20',
  'minimum_real_setback': '5',
  'minimum_side_setback': '2.5',
  'planning_pathway': 'Complying Development',
  'zone': 'SP3',
  'zone_description': 'Tourist'},
 {'additional_criteria': 'No commercial use allowed in garage',
  'category': 'category13',
  'development_type': 'Outbuilding (Garage)',
  'maximum_area': '60',
  'maximum_building_height': '3.5',
  'maximum_percentage_of_lot_used': '0.5',
  'minimum_front_setback': '4',
  'minimum_lot_size': '500',
  'minimum_lot_width': '15',
  'minimum_real_setback': '3',
  'minimum_side_setback': '0.9',
  'planning_pathway': 'Complying Development',
  'zone': 'MU1',
  'zone_description': 'Mixed Use'},
 {'additional_criteria': 'Any',
  'category': 'category14',
  'development_type': 'Outbuilding (Garage)',
  'maximum_area': 'Any',
  'maximum_building_height': 'Any',
  'maximum_percentage_of_lot_used': 'Any',
  'minimum_front_setback': 'Any',
  'minimum_lot_size': 'Any',
  'minimum_lot_width': 'Any',
  'minimum_real_setback': 'Any',
  'minimum_side_setback': 'Any',
  'planning_pathway': 'Local Council',
  'zone': 'Any',
  'zone_description': 'Any'},
 {'additional_criteria': 'Any',
  'category': 'category15',
  'development_type': 'Outbuilding (Carport)',
  'maximum_area': 'Any',
  'maximum_building_height': 'Any',
  'maximum_percentage_of_lot_used': 'Any',
  'minimum_front_setback': 'Any',
  'minimum_lot_size': 'Any',
  'minimum_lot_width': 'Any',
  'minimum_real_setback': 'Any',
  'minimum_side_setback': 'Any',
  'planning_pathway': 'Local Council',
  'zone': 'Any',
  'zone_description': 'Any'},
 {'additional_criteria': 'Any',
  'category': 'category16',
  'development_type': 'New Dwelling',
  'maximum_area': 'Any',
  'maximum_building_height': 'Any',
  'maximum_percentage_of_lot_used': 'Any',
  'minimum_front_setback': 'Any',
  'minimum_lot_size': 'Any',
  'minimum_lot_width': 'Any',
  'minimum_real_setback': 'Any',
  'minimum_side_setback': 'Any',
  'planning_pathway': 'Local Council',
  'zone': 'Any',
  'zone_description': 'Any'}]