# Generated by Django 5.1 on 2024-09-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('council', models.CharField(max_length=50, null=True)),
                ('datatime', models.DateTimeField(auto_now_add=True)),
                ('user_message', models.CharField(max_length=3000, null=True)),
                ('ai_message', models.CharField(max_length=3000, null=True)),
            ],
            options={
                'db_table': 'chat_history',
            },
        ),
    ]
