# Generated by Django 5.1 on 2024-10-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user_message', models.CharField(max_length=3000, null=True)),
                ('ai_message', models.CharField(max_length=3000, null=True)),
            ],
            options={
                'db_table': 'chat_history',
            },
        ),
        migrations.CreateModel(
            name='ChatHistoryClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('log', models.CharField(max_length=5000, null=True)),
                ('summary', models.CharField(max_length=5000, null=True)),
                ('priority', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'chat_history_client',
            },
        ),
    ]
