# Generated by Django 5.1 on 2024-10-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=50, null=True)),
                ('sub', models.CharField(max_length=50, null=True)),
                ('oid', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('messages', models.JSONField()),
            ],
            options={
                'db_table': 'chat_history',
            },
        ),
    ]
