# Generated by Django 5.1 on 2024-10-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='sub',
            new_name='user_uuid',
        ),
    ]
