# Generated by Django 5.1 on 2024-09-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='council',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='priority',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='summary',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
