# Generated by Django 5.1 on 2024-10-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_sub_chathistory_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='oid',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='username',
        ),
    ]
