# Generated by Django 5.1 on 2024-09-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chathistory_council_chathistory_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
