# Generated by Django 5.1 on 2024-10-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chathistory_oid_remove_chathistory_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='messages',
            field=models.JSONField(null=True),
        ),
    ]
