# Generated by Django 5.1 on 2024-09-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chathistory_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='datatime',
            new_name='datetime',
        ),
    ]
