# Generated by Django 5.1 on 2024-09-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_datatime_chathistory_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistoryClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('log', models.CharField(max_length=5000, null=True)),
                ('summary', models.CharField(max_length=5000, null=True)),
                ('priority', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'chat_history_client',
            },
        ),
    ]
