# Generated by Django 5.1 on 2024-09-20 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chathistoryclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='summary',
        ),
    ]
