# Generated by Django 5.1 on 2024-10-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chathistory_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistoryclient',
            name='user_id',
        ),
    ]
