# Generated by Django 5.1 on 2024-10-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_chathistoryclient_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistoryclient',
            name='user_uuid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
