# Generated by Django 5.1 on 2024-10-02 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chathistoryclient_user_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='user_id',
            new_name='user_uuid',
        ),
    ]
