# Generated by Django 5.1 on 2024-10-02 04:11

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistoryClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=50, null=True)),
                ('role_id', models.CharField(max_length=50, null=True)),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('project_id', models.CharField(max_length=50, null=True)),
                ('content', models.DateTimeField(auto_now_add=True)),
                ('content_vector', pgvector.django.vector.VectorField(null=True)),
                ('metadata', models.CharField(max_length=3000, null=True)),
                ('title', models.CharField(max_length=3000, null=True)),
                ('source', models.CharField(max_length=3000, null=True)),
            ],
            options={
                'db_table': 'knowledgebase',
            },
        ),
    ]
